### ISSUE TITLE
Structured logging

### ISSUE THREAD

**Issue by chuckha** [heptiolabs/namespace-deleter#3]
The logging situation here is not very good. Please improve it by using the [logrus library](https://github.com/sirupsen/logrus).

**Comment by sanketjpatel** [comment]
Hi! I'd like to contribute, but I see there's an open PR which is good to merge - https://github.com/heptiolabs/namespace-deleter/pull/2

Should I base this feature off `heptiolabs:master` or `amy:master`?

@chuckha @amy

**Comment by chuckha** [comment]
@sanketjpatel hi! Thanks for bringing this up, I just merged it so you can base your work off master now!

**Comment by sanketjpatel** [comment]
Thank you! Also, I'm a Go newbie so it would be very helpful if you could give me some pointers on the PR 😄 

Will open it shortly

**Comment by chuckha** [comment]
thank you!
